# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='index.py',
    version='0.10.9',
    description='An easy-to-use asynchronous web framework based on ASGI.',
    python_requires='==3.*,>=3.6.0',
    project_urls={
        "documentation": "https://index-py.abersheeran.com/",
        "homepage": "https://github.com/abersheeran/index.py",
        "repository": "https://github.com/abersheeran/index.py"
    },
    author='abersheeran',
    author_email='me@abersheeran.com',
    license='Apache-2.0',
    classifiers=[
        'License :: OSI Approved :: Apache Software License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: Implementation :: CPython'
    ],
    entry_points={"console_scripts": ["index-cli = indexpy.cli:main"]},
    packages=[
        'example.example', 'example.utils', 'example.views',
        'example.views.about', 'example.views.openapi', 'example.wsgi_example',
        'indexpy', 'indexpy.http', 'indexpy.openapi', 'indexpy.websocket'
    ],
    package_dir={"": "."},
    package_data={
        "indexpy": ["*.typed"],
        "indexpy.openapi": ["*.html"]
    },
    install_requires=[
        'a2wsgi==0.*,>=0.3.5', 'aiofiles==0.*,>=0.5.0',
        'contextvars==2.*,>=2.4.0; python_version == "3.6.*" and python_version >= "3.6.0"',
        'jinja2==2.*,>=2.10.3', 'pydantic==1.*,>=1.5.0',
        'python-multipart==0.*,>=0.0.5', 'pyyaml==5.*,>=5.3.0',
        'starlette==0.*,>=0.13.1',
        'typing-extensions==3.*,>=3.7.4; python_version < "3.8"',
        'uvicorn==0.*,>=0.11.3', 'watchdog==0.*,>=0.10.2'
    ],
    extras_require={
        "dev": [
            "black", "django==3.*,>=3.0.2", "flake8", "mkdocs",
            "mkdocs-material", "mypy", "pytest-asyncio==0.*,>=0.12.0",
            "pytest-cov==2.*,>=2.8.1"
        ],
        "gunicorn": ["gunicorn==20.*,>=20.0.4"],
        "pytest": ["pytest==5.*,>=5.4.2"],
        "requests": ["requests==2.*,>=2.23.0"],
        "test": ["pytest==5.*,>=5.4.2", "requests==2.*,>=2.23.0"]
    },
)
