name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
    paths:
      - ".github/workflows/ci.yml"
      - "**.py"
      - "!xing/__version__.py"
      - poetry.lock
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/ci.yml"
      - "**.py"
      - "!xing/__version__.py"
      - poetry.lock

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
        os: [windows-latest, ubuntu-latest, macos-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: pdm-project/setup-pdm@v3
        name: Setup Python and PDM
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          version: 2.4.2
          enable-pep582: true # Enable PEP 582 package loading globally
          cache: true
      - name: Install dependencies
        run: pdm sync
      - name: Static type and format checking
        run: |
          export PATH=$PATH:$(pdm info --packages)/bin
          python script/check.py
      - name: Generate coverage report
        run: |
          export PATH=$PATH:$(pdm info --packages)/bin
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
          directory: ./coverage/reports/
          flags: unittests
          env_vars: OS,PYTHON
          fail_ci_if_error: false
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true

  publish:
    needs: tests
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: pdm-project/setup-pdm@v3
        name: Setup Python and PDM
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          version: 2.4.2
          enable-pep582: true # Enable PEP 582 package loading globally
          cache: true

      - name: Publish
        run: pdm publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
